---
driver:
  name: docker

provisioner:
  chef_omnibus_root: /opt/chef

driver_config:
  require_chef_omnibus: false
  use_sudo: false
  privileged: true
  private_key: .kitchen/docker_id_rsa
  public_key: .kitchen/docker_id_rsa.pub

platforms:
<% %w(6.7 7.2).each do |centos_version| %>
  - name: centos-<%= centos_version %>
    driver_config:
      provision_command:
        - yum makecache && yum -y install autoconf bison flex gcc gcc-c++ kernel-devel make m4 curl tar
        - curl -L https://www.opscode.com/chef/install.sh | bash -s -- -v 12.14.61 -d /tmp/vagrant-cache/vagrant_omnibus/
        - env GEM_HOME=/tmp/verifier/gems GEM_PATH=/tmp/verifier/gems GEM_CACHE=/tmp/verifier/gems/cache /opt/chef/embedded/bin/gem install --no-ri --no-rdoc net-ssh -v '2.9.2'
        - env GEM_HOME=/tmp/verifier/gems GEM_PATH=/tmp/verifier/gems GEM_CACHE=/tmp/verifier/gems/cache /opt/chef/embedded/bin/gem install --no-ri --no-rdoc thor busser busser-serverspec serverspec rspec-expectations
        - chown -R kitchen:kitchen /tmp/verifier
      volume:
      <% if File.exist?("#{ENV['HOME']}/.vagrant.d/cache/inviqa/centos-#{centos_version.sub(/^(\d)\..*/, '\1')}-minimal") %>
        - <%= ENV['HOME'] %>/.vagrant.d/cache/inviqa/centos-<%= centos_version %>-minimal/chef:/var/chef/cache
        - <%= ENV['HOME'] %>/.vagrant.d/cache/inviqa/centos-<%= centos_version %>-minimal/vagrant_omnibus:/tmp/vagrant-cache/vagrant_omnibus/
        - <%= ENV['HOME'] %>/.vagrant.d/cache/inviqa/centos-<%= centos_version %>-minimal/yum:/var/cache/yum
      <% end %>
    <% if centos_version.to_f >= 7.0 %>
      run_command: /usr/lib/systemd/systemd
    <% end %>
    run_list:
      - recipe[yum]
<% end %>
